export const sites = [
  {
    id: "1",
    tipo: "sites",
    name: "Hot Sites",
    price: "99,90",
    entrega: "Entregue em 1 dia",
    paginas: "Tudo em uma página",
    topicos: "5 tópicos de conteúdo",
    formularios: "Formulário de contacto",
    btn_class: "btn btn-lg btn-block btn-primary",
  },
  {
    id: "2",
    tipo: "sites",
    name: "Site Básico",
    price: "450",
    entrega: "Prazo 30 dias",
    paginas: "Até 10 páginas",
    topicos: "Até 10 Tópicos",
    formularios: "Até 2 Formulários de contacto",
    btn_class: "btn btn-lg btn-block btn-outline-primary",
  },
  {
    id: "3",
    tipo: "sites",
    name: "Portal de Conteúdo",
    price: "1200",
    entrega: "Prazo a combinar",
    paginas: "Conteúdo ilimitado",
    topicos: "Tópicos ilimitados",
    formularios: "Formulários ilimitados",
    btn_class: "btn btn-lg btn-block btn-primary",
  },
  {
    id: "4",
    tipo: "hospedagem",
    name: "Plano Mensal",
    price: "10",
    entrega: "Mensal",
    paginas: "Hospedagem Linux / PHP",
    topicos: "25 contas de email 2 GB",
    formularios: "Espaço Web 100 GB",
    btn_class: "btn btn-lg btn-block btn-primary",
  },
  {
    id: "5",
    tipo: "hospedagem",
    name: "Plano Semestral",
    price: "50",
    entrega: "1 mes GRÁTIS",
    paginas: "Hospedagem Linux / PHP",
    topicos: "100 contas de email 2 GB",
    formularios: "Espaço Web 200 GB",
    btn_class: "btn btn-lg btn-block btn-primary",
  },
  {
    id: "6",
    tipo: "hospedagem",
    name: "Plano Anual",
    price: "100",
    entrega: "2 meses GRÁTIS!",
    paginas: "Hospedagem Linux / PHP",
    topicos: "500 contas de email 2 GB",
    formularios: "Espaço Web 500 GB",
    btn_class: "btn btn-lg btn-block btn-outline-primary",
  },
];
